name: Matt Mooney
favicon: null
layout_spectrum: 0.36481
typography_spectrum: 0.6455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edeef0'
    - '#232939'
    - '#cea895'
    - '#4390f4'
    - '#9a6d5a'
  brandStrength: 0.125
  lightness: 0.4375
  saturation: 0.6211518519558012
  rhythmicContrast: 0.25
purpose: []
